### ISSUE TITLE
Support for double wireless switch?

### ISSUE THREAD

**Issue by 12nick12** [Yoda-x/ha-zha-new#17]
Does this support Xiaomi double wireless switch? I was able to get the switch added, but I don't see it in the front end. WARNING (MainThread) [bellows.zigbee.endpoint] [0x3d9f:2] Message on unknown cluster 0x0006. The :2 changes depending one which button I hit so I think it's working, but I'm not sure where to go to get it functioning.

**Comment by Yoda-x** [comment]
A switch should work. I assume it's the battery driven model and not the one that replaces the build-in wall switches with commercial power. Plesse try to keep tthe switch alive until the init is complete.
This is a commen issue with xiaomi battery driven devices. They join  the network, but go to sleep before the controller can identify them. Just push the button every second until both switches are in the web GUI.
This can take up to 40 sec

**Comment by 12nick12** [comment]
Ah ok. Thank you. What should they show up as? Does it just show up as the normal "binary_sensor.wall_switch_both_blahblahblah"? Thank you for your response BTW and your hard work. I'm so happy I'm able to get rid of my hue hub.

**Comment by 12nick12** [comment]
Do I hold the switches down like I'm trying to pair them or just tap them like I'm trying to use them?

**Comment by Yoda-x** [comment]
It's a short tap, like if you use them. Just to prevent them going to sleep.
you should also add something like this to your config, It's assign a component type to the device, which overrides the built-in detection, based on device-ids (which not works, because xiaomi not follows the rules)
```
device_config:`
  "yourmac-1":
    type: switch
  "yourmac-2":
    type: switch

Indention matters as usual

**Comment by 12nick12** [comment]
Awesome thank you. I added the mac-1 and so one. Is there a way to define what cluster 0x0006? It still says "Message on unknown cluster 0x0006" It never showed up in hass even after click if for a while. It showed up int he db tho

````
zha_new:
  usb_path: /dev/zigbee
  database_path: /home/hass/.homeassistant/zigbee.db
  device_config:
    "00:xx:xx:xx:xx:xx:xx:bf-1":
      template: switch
    "00:xx:xx:xx:xx:xx:xx:bf-2":
      template: switch
    "00:xx:xx:xx:xx:xx:xx:bf-3":
      template: switch
````
