### ISSUE TITLE
Aqara smart button WXKG11LM detected as lumi_remote_b1acn01

### ISSUE THREAD

**Issue by estevez-dev** [Yoda-x/ha-zha-new#56]
It seams this device is not supported at all. Am I right? The model is: WXKG11LM
It is joined, initialized but no entity created.

**Comment by KLUSEK** [comment]
https://github.com/Yoda-x/ha-zha-new/issues/45

**Comment by estevez-dev** [comment]
Thanks, but I can't even pair it =(

**Comment by estevez-dev** [comment]
I'm simply don't know where to start. Which logs I need to enable for ex?

**Comment by KLUSEK** [comment]
You need to use preview branch of zha_new. Then pair the device.

**Comment by estevez-dev** [comment]
@KLUSEK Ok. Is it possible to save my Aqara devices already connected to HA? Last time I updated zha_new all my devices was lost their entities.

**Comment by KLUSEK** [comment]
I don't know that, I'm not the Author :)

**Comment by estevez-dev** [comment]
@KLUSEK I know, I just wanted to know was your aqara devices disappeared after updating zha_new.

Ok, now I have paired it. But it is detected as ```binary_sensor.lumi_lumiremoteb1acn01_01ef39e8_1``` and state is always ```off```

**Comment by KLUSEK** [comment]
Now just used automation.

Check mine:

`- alias: 'Aqara bedroom button'
  hide_entity: True
  initial_state: True
  trigger:
    platform: event
    event_type: click
    # optional
    event_data:
      entity_id: binary_sensor.lumi_lumisensor_switchaq2_01e7a174_1_on_off
      channel: OnOff
      data: 1
  action:
    - service: switch.toggle
      data:
        entity_id: 'switch.bedroom_spotlights'`

**Comment by estevez-dev** [comment]
Ah, it is an event! Now I understood how it should work, but it still doesn't =(
My automation:
```
  alias: Badtime button single click
  trigger:
  - event_data:
      channel: OnOff
      data: 1
      entity_id: binary_sensor.lumi_lumiremoteb1acn01_01ef39e8_1
    event_type: click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room
    service: light.toggle
```
No errors in log. Log is enabled for:
```
    custom_components.zha_new: debug
    custom_components.device.lumi_sensor_magnet_aq2: debug
    custom_components.binary_sensor.zha_new: debug
    custom_components.device.lumi_sensor_switch_aq2: debug
    custom_components.binary_sensor.lumi_lumiremote: debug
```
