### ISSUE TITLE
Support of Aqara devices needs different device names

### ISSUE THREAD

**Issue by ChristianHackAMS** [Yoda-x/ha-zha-new#6]
```
zha_new:
    usb_path: /dev/ttyUSB1
    database_path: /config/zigbee.db
    device_config: 
# HT sensor    
      "00:15:8d:00:01:9f:df:de-1":
        type: sensor
        in_cluster: [0x0000, 0x0001, 0x0003, 0x0009, 0xff01, 0xffff]
        config_report:
          - [ 0x0405, 0, 1, 120, 5]
          - [ 0x0403, 0, 1, 120, 5]
          - [ 0x0402, 0, 1, 120, 5]
# Door sensor
      "00:15:8d:00:01:e4:4d:d3-1":
        type: binary_sensor
        in_cluster: [ 0, 25, 3,  0xffff ]
        out_cluster: [ 0, 3, 4, 5, 8, 6, 25]
        config_report:
          - [ 1, 20, 1, 1200, 10]
          - [ 6, 0, 1, 120, '01']
# Motion sensor
      "00:15:8d:00:01:65:78:d6-1":
        type: binary_sensor
        in_cluster: [ 0, 1, 25, 3,  0xffff ]
        out_cluster: [ 0,1, 3, 4, 5, 8, 6, 25]
        config_report:
          - [ 1, 20, 1, 1200, 10]
          - [ 0x406, 0, 1, 1200, '01']
```

Have these three Aqara sensors working but need devices symlinks (pressure received but not working) :

```
lrwxrwxrwx 1 root root   21 Jan  7 18:18 lumi_sensor_magnet_aq2.py -> lumi_sensor_magnet.py
lrwxrwxrwx 1 root root   21 Jan  7 18:19 lumi_sensor_motion_aq2.py -> lumi_sensor_magnet.py
```

This at least gets them working initially

Still having some problems with devices leaving the network though.
